language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      python: 2.7
      env:
        - TRAVIS_CLANG=clang-4.0
        - TRAVIS_CLANGPP=clang++-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.3
      env:
        - TRAVIS_CLANG=clang-4.0
        - TRAVIS_CLANGPP=clang++-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.4
      env:
        - TRAVIS_CLANG=clang-4.0
        - TRAVIS_CLANGPP=clang++-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.5
      env:
        - TRAVIS_CLANG=clang-4.0
        - TRAVIS_CLANGPP=clang++-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.6
      env:
        - TRAVIS_CLANG=clang-4.0
        - TRAVIS_CLANGPP=clang++-4.0
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0

before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      command -v pip || { brew update && brew install python; };
    fi

install:
  - pip --version
  - pip install --upgrade pip
  - pip install -r tests/requirements.txt

script:
  - pip install .
  - pip install ./tests
  - lit -v tests
  - python setup.py sdist

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3b71470714f6eaa03bc
    on_success: change
    on_failure: always
    on_start: never
