language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      python: 2.7
      env:
        - TRAVIS_CLANG=clang-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.3
      env:
        - TRAVIS_CLANG=clang-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.4
      env:
        - TRAVIS_CLANG=clang-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.5
      env:
        - TRAVIS_CLANG=clang-4.0
    - os: linux
      dist: trusty
      sudo: false
      python: 3.6
      env:
        - TRAVIS_CLANG=clang-4.0
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0
      - cmake
      - scons
      - qt4-qmake

before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      command -v pip || { brew update && brew install python; };
    fi

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit
  - pip install pep8

script:
  - pip install .
  - lit -v tests
  - python setup.py sdist

deploy:
  provider: pypi
  user: "rizsotto"
  password:
    secure: "ModXQEmzuckPZ3KhHR8sU7Or2ivqfifY15/fTFZ5h3zhVfeqFjIdjcqb9lZSM3tezCKgsPv6jCC5T92tY/Ul78tUOuA71rWlqkiacxrMOF3AprXr7QJ/+ssY+AmRS+Mb1e/JgeRra+2AUIwZfLPK4sV8mvbvRUebw9M/xGf9eIc="
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3b71470714f6eaa03bc
    on_success: change
    on_failure: always
    on_start: never
